import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, '..');
const contractsDir = path.resolve(packageRoot, 'src');
const artifactsDir = path.resolve(packageRoot, 'artifacts');

export interface CompiledArtifact {
  contractName: string;
  sourceName: string;
  abi: any[];
  bytecode: string;
  deployedBytecode: string;
}

export function compileAll(): Record<string, CompiledArtifact> {
  const solFiles = fs.readdirSync(contractsDir).filter(f => f.endsWith('.sol'));

  if (solFiles.length === 0) {
    throw new Error(`No .sol files found in ${contractsDir}`);
  }

  const sources: Record<string, { content: string }> = {};
  for (const file of solFiles) {
    sources[file] = {
      content: fs.readFileSync(path.join(contractsDir, file), 'utf8')
    };
  }

  const input = {
    language: 'Solidity',
    sources,
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      },
      evmVersion: 'cancun',
      outputSelection: {
        '*': {
          '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object', 'metadata']
        }
      }
    }
  };

  console.log(`Compiling ${solFiles.length} Solidity contract(s)...`);
  const output = JSON.parse(solc.compile(JSON.stringify(input)));

  if (output.errors) {
    let hasError = false;
    for (const error of output.errors) {
      if (error.severity === 'error') {
        console.error(`\x1b[31m[ERROR]\x1b[0m ${error.formattedMessage}`);
        hasError = true;
      } else {
        console.warn(`\x1b[33m[WARN]\x1b[0m ${error.formattedMessage}`);
      }
    }
    if (hasError) {
      throw new Error('Solidity compilation failed with errors');
    }
  }

  fs.mkdirSync(artifactsDir, { recursive: true });

  const artifacts: Record<string, CompiledArtifact> = {};

  for (const [sourceFile, contracts] of Object.entries(output.contracts as Record<string, Record<string, any>>)) {
    for (const [contractName, data] of Object.entries(contracts)) {
      const artifact: CompiledArtifact = {
        contractName,
        sourceName: sourceFile,
        abi: data.abi,
        bytecode: '0x' + data.evm.bytecode.object,
        deployedBytecode: '0x' + data.evm.deployedBytecode.object
      };

      artifacts[contractName] = artifact;
      const artifactPath = path.join(artifactsDir, `${contractName}.json`);
      fs.writeFileSync(artifactPath, JSON.stringify(artifact, null, 2), 'utf8');
      console.log(`✓ Wrote artifact: ${artifactPath} (${(artifact.bytecode.length / 2).toFixed(0)} bytes)`);
    }
  }

  // Generate TypeScript artifacts module in src/artifacts.ts
  const tsContent = `// Auto-generated by scripts/compile.ts. Do not edit manually.
export interface ContractArtifact {
  readonly contractName: string;
  readonly sourceName: string;
  readonly abi: readonly any[];
  readonly bytecode: string;
  readonly deployedBytecode: string;
}

${Object.entries(artifacts).map(([name, art]) => `
export const ${name}Artifact: ContractArtifact = {
  contractName: ${JSON.stringify(art.contractName)},
  sourceName: ${JSON.stringify(art.sourceName)},
  abi: ${JSON.stringify(art.abi)},
  bytecode: ${JSON.stringify(art.bytecode)},
  deployedBytecode: ${JSON.stringify(art.deployedBytecode)},
} as const;

export const ${name}Abi = ${name}Artifact.abi;
export const ${name}Bytecode = ${name}Artifact.bytecode;
`).join('\n')}
`;

  fs.writeFileSync(path.join(contractsDir, 'artifacts.ts'), tsContent, 'utf8');
  console.log(`✓ Generated ${path.join(contractsDir, 'artifacts.ts')}`);

  return artifacts;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    compileAll();
    console.log('Solidity compilation complete.');
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}
