#!/usr/bin/env bash
set -euo pipefail

repo=$(git rev-parse --show-toplevel)
cd "$repo"

snapshot=${PROTO_INVENTORY_SNAPSHOT:-docs/protocol/protobuf-inventory.snapshot}
mode=${1:---check}
if [[ "$mode" != "--check" && "$mode" != "--write" ]]; then
  echo "usage: $0 [--check|--write]" >&2
  exit 2
fi
command -v protoc >/dev/null 2>&1 || {
  echo "protoc is required to check the protobuf inventory" >&2
  exit 2
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
actual="$tmp/protobuf-inventory.snapshot"

classify() {
  case "$1" in
    backend/bitcoinsuite/bitcoinsuite-chronik-client/proto/chronik.proto)
      owner="Chronik client dependency" family="Chronik upstream RPC" disposition="third-party/non-CashWeb" group="chronik-upstream" ;;
    backend/cashweb/cashweb-http-utils/proto/http.proto)
      owner="CashWeb HTTP utilities" family="legacy HTTP error" disposition="transport-only" group="http-error" ;;
    backend/cashweb/cashweb-payload/proto/payload.proto)
      owner="cashweb-payload verifier" family="Lotus signed payload and burn evidence" disposition="retained constrained legacy reader" group="lotus-signed-payload-backend" ;;
    backend/cashweb/cashweb-registry/proto/broadcast.proto)
      owner="cashweb-registry Lotus topics" family="Lotus broadcast storage" disposition="retained constrained legacy reader" group="lotus-broadcast-backend" ;;
    backend/cashweb/cashweb-registry/proto/monad_message.proto)
      owner="cashweb-registry Monad mailbox" family="Monad stamped direct message" disposition="retained constrained legacy reader" group="monad-message-mirror" ;;
    backend/cashweb/cashweb-registry/proto/monad_profile.proto)
      owner="cashweb-registry Monad profiles" family="Monad profile discovery" disposition="retained constrained legacy reader" group="monad-profile-backend" ;;
    backend/cashweb/cashweb-registry/proto/registry.proto)
      owner="cashweb-registry legacy directory" family="Lotus registry and federation transport" disposition="retained reader plus transport-only responses" group="lotus-registry-backend" ;;
    backend/cashweb/cashweb-registry/proto/topic_message.proto)
      owner="cashweb-registry Monad topics" family="Monad topic post vote and discovery" disposition="retained constrained legacy reader" group="monad-topic-mirror" ;;
    packages/cashweb/bip70/proto/paymentrequest.proto)
      owner="CashWeb BIP70/POP client" family="legacy admission payment and bearer token" disposition="retained constrained legacy reader" group="bip70-pop" ;;
    packages/cashweb/registry/proto/broadcast.proto)
      owner="CashWeb registry client" family="Lotus broadcast application data" disposition="retained constrained legacy reader" group="lotus-broadcast-client" ;;
    packages/cashweb/registry/proto/metadata.proto)
      owner="CashWeb registry client" family="Lotus registry and Monad profile transport" disposition="retained reader plus transport-only responses" group="lotus-registry-client" ;;
    packages/cashweb/relay/proto/filters.proto)
      owner="CashWeb relay client" family="legacy inbox filters" disposition="retained constrained legacy reader" group="relay-filters" ;;
    packages/cashweb/relay/proto/monad_message.proto)
      owner="CashWeb relay client" family="Monad stamped direct message" disposition="retained constrained legacy reader" group="monad-message-mirror" ;;
    packages/cashweb/relay/proto/p2pkh.proto)
      owner="CashWeb relay client" family="legacy P2PKH transport" disposition="transport-only" group="relay-p2pkh" ;;
    packages/cashweb/relay/proto/relay.proto)
      owner="CashWeb relay client" family="legacy relay profile message and pages" disposition="retained constrained legacy reader" group="relay-core" ;;
    packages/cashweb/relay/proto/stealth.proto)
      owner="CashWeb relay client" family="legacy stealth transport" disposition="transport-only" group="relay-stealth" ;;
    packages/cashweb/signed_payload/proto/payload.proto)
      owner="CashWeb signed-payload client" family="Lotus signed payload and burn evidence" disposition="retained constrained legacy reader" group="lotus-signed-payload-client" ;;
    packages/wallet/proto/topic_message.proto)
      owner="wallet Monad topics" family="Monad topic post vote and discovery" disposition="retained constrained legacy reader" group="monad-topic-mirror" ;;
    *)
      echo "unclassified tracked protobuf source: $1" >&2
      exit 1 ;;
  esac
}

{
  echo "# Generated by docs/protocol/check-protobuf-inventory.sh; do not edit."
  echo "# Every descriptor message, enum, and field inherits its source classification."
  while IFS= read -r source; do
    classify "$source"
    descriptor="$tmp/descriptor.pb"
    diagnostics="$tmp/protoc.stderr"
    if ! protoc \
      -I "$repo" \
      -I "$repo/backend/cashweb/cashweb-payload/proto" \
      -I "$repo/backend/cashweb/cashweb-registry/proto" \
      --descriptor_set_out="$descriptor" \
      "$source" 2>"$diagnostics"; then
      cat "$diagnostics" >&2
      exit 1
    fi
    printf 'source: %s\nowner: %s\nfamily: %s\ndisposition: %s\nexplicit_source_group: %s\n' \
      "$source" "$owner" "$family" "$disposition" "$group"
    echo "descriptor: |"
    protoc --decode=google.protobuf.FileDescriptorSet google/protobuf/descriptor.proto \
      < "$descriptor" | sed 's/^/  /'
    echo "---"
  done < <(git ls-files '*.proto' | LC_ALL=C sort)
} > "$actual"

if [[ "$mode" == "--write" ]]; then
  cp "$actual" "$snapshot"
  echo "wrote $snapshot"
  exit 0
fi

if ! cmp -s "$actual" "$snapshot"; then
  echo "protobuf inventory is stale or incomplete; run $0 --write and review the diff" >&2
  diff -u "$snapshot" "$actual" >&2 || true
  exit 1
fi
echo "protobuf inventory is current"
