// source: topic_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

goog.exportSymbol('proto.cashweb.registry.ListTopicsResponse', null, global);
goog.exportSymbol('proto.cashweb.registry.MonadTopicPost', null, global);
goog.exportSymbol('proto.cashweb.registry.MonadTopicPostView', null, global);
goog.exportSymbol('proto.cashweb.registry.MonadTopicPostViews', null, global);
goog.exportSymbol('proto.cashweb.registry.MonadTopicVote', null, global);
goog.exportSymbol('proto.cashweb.registry.StoredMonadTopicPost', null, global);
goog.exportSymbol('proto.cashweb.registry.StoredMonadTopicVoteEntry', null, global);
goog.exportSymbol('proto.cashweb.registry.TopicDiscoveryEntry', null, global);
goog.exportSymbol('proto.cashweb.registry.TopicDiscoveryStats', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadTopicPost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.MonadTopicPost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadTopicPost.displayName = 'proto.cashweb.registry.MonadTopicPost';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadTopicVote = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.MonadTopicVote, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadTopicVote.displayName = 'proto.cashweb.registry.MonadTopicVote';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.StoredMonadTopicPost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.StoredMonadTopicPost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.StoredMonadTopicPost.displayName = 'proto.cashweb.registry.StoredMonadTopicPost';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.StoredMonadTopicVoteEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.StoredMonadTopicVoteEntry.displayName = 'proto.cashweb.registry.StoredMonadTopicVoteEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadTopicPostView = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.MonadTopicPostView, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadTopicPostView.displayName = 'proto.cashweb.registry.MonadTopicPostView';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadTopicPostViews = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cashweb.registry.MonadTopicPostViews.repeatedFields_, null);
};
goog.inherits(proto.cashweb.registry.MonadTopicPostViews, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadTopicPostViews.displayName = 'proto.cashweb.registry.MonadTopicPostViews';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.TopicDiscoveryStats = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.TopicDiscoveryStats, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.TopicDiscoveryStats.displayName = 'proto.cashweb.registry.TopicDiscoveryStats';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.TopicDiscoveryEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.TopicDiscoveryEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.TopicDiscoveryEntry.displayName = 'proto.cashweb.registry.TopicDiscoveryEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.ListTopicsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cashweb.registry.ListTopicsResponse.repeatedFields_, null);
};
goog.inherits(proto.cashweb.registry.ListTopicsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.ListTopicsResponse.displayName = 'proto.cashweb.registry.ListTopicsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadTopicPost.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadTopicPost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadTopicPost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicPost.toObject = function(includeInstance, msg) {
  var f, obj = {
topic: jspb.Message.getFieldWithDefault(msg, 1, ""),
parentPostHash: msg.getParentPostHash_asB64(),
rawBurnTx: msg.getRawBurnTx_asB64(),
encryptedPayload: msg.getEncryptedPayload_asB64(),
payloadHash: msg.getPayloadHash_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadTopicPost}
 */
proto.cashweb.registry.MonadTopicPost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadTopicPost;
  return proto.cashweb.registry.MonadTopicPost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadTopicPost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadTopicPost}
 */
proto.cashweb.registry.MonadTopicPost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTopic(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setParentPostHash(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawBurnTx(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncryptedPayload(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPayloadHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicPost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadTopicPost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadTopicPost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicPost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getParentPostHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getRawBurnTx_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getEncryptedPayload_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getPayloadHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional string topic = 1;
 * @return {string}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cashweb.registry.MonadTopicPost} returns this
 */
proto.cashweb.registry.MonadTopicPost.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes parent_post_hash = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getParentPostHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes parent_post_hash = 2;
 * This is a type-conversion wrapper around `getParentPostHash()`
 * @return {string}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getParentPostHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getParentPostHash()));
};


/**
 * optional bytes parent_post_hash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getParentPostHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getParentPostHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getParentPostHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadTopicPost} returns this
 */
proto.cashweb.registry.MonadTopicPost.prototype.setParentPostHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes raw_burn_tx = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getRawBurnTx = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes raw_burn_tx = 3;
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {string}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getRawBurnTx_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawBurnTx()));
};


/**
 * optional bytes raw_burn_tx = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getRawBurnTx_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawBurnTx()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadTopicPost} returns this
 */
proto.cashweb.registry.MonadTopicPost.prototype.setRawBurnTx = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes encrypted_payload = 4;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getEncryptedPayload = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes encrypted_payload = 4;
 * This is a type-conversion wrapper around `getEncryptedPayload()`
 * @return {string}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getEncryptedPayload_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncryptedPayload()));
};


/**
 * optional bytes encrypted_payload = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncryptedPayload()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getEncryptedPayload_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncryptedPayload()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadTopicPost} returns this
 */
proto.cashweb.registry.MonadTopicPost.prototype.setEncryptedPayload = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bytes payload_hash = 5;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getPayloadHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes payload_hash = 5;
 * This is a type-conversion wrapper around `getPayloadHash()`
 * @return {string}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getPayloadHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPayloadHash()));
};


/**
 * optional bytes payload_hash = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPayloadHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicPost.prototype.getPayloadHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPayloadHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadTopicPost} returns this
 */
proto.cashweb.registry.MonadTopicPost.prototype.setPayloadHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadTopicVote.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadTopicVote.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadTopicVote} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicVote.toObject = function(includeInstance, msg) {
  var f, obj = {
targetPayloadHash: msg.getTargetPayloadHash_asB64(),
rawBurnTx: msg.getRawBurnTx_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadTopicVote}
 */
proto.cashweb.registry.MonadTopicVote.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadTopicVote;
  return proto.cashweb.registry.MonadTopicVote.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadTopicVote} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadTopicVote}
 */
proto.cashweb.registry.MonadTopicVote.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTargetPayloadHash(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawBurnTx(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicVote.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadTopicVote.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadTopicVote} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicVote.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetPayloadHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getRawBurnTx_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional bytes target_payload_hash = 1;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadTopicVote.prototype.getTargetPayloadHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes target_payload_hash = 1;
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {string}
 */
proto.cashweb.registry.MonadTopicVote.prototype.getTargetPayloadHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTargetPayloadHash()));
};


/**
 * optional bytes target_payload_hash = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicVote.prototype.getTargetPayloadHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTargetPayloadHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadTopicVote} returns this
 */
proto.cashweb.registry.MonadTopicVote.prototype.setTargetPayloadHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes raw_burn_tx = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadTopicVote.prototype.getRawBurnTx = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes raw_burn_tx = 2;
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {string}
 */
proto.cashweb.registry.MonadTopicVote.prototype.getRawBurnTx_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawBurnTx()));
};


/**
 * optional bytes raw_burn_tx = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicVote.prototype.getRawBurnTx_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawBurnTx()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadTopicVote} returns this
 */
proto.cashweb.registry.MonadTopicVote.prototype.setRawBurnTx = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.StoredMonadTopicPost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.StoredMonadTopicPost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadTopicPost.toObject = function(includeInstance, msg) {
  var f, obj = {
post: (f = msg.getPost()) && proto.cashweb.registry.MonadTopicPost.toObject(includeInstance, f),
senderAddress: msg.getSenderAddress_asB64(),
txHash: msg.getTxHash_asB64(),
timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
networkTag: msg.getNetworkTag_asB64(),
cborPostFrame: msg.getCborPostFrame_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.StoredMonadTopicPost}
 */
proto.cashweb.registry.StoredMonadTopicPost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.StoredMonadTopicPost;
  return proto.cashweb.registry.StoredMonadTopicPost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.StoredMonadTopicPost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.StoredMonadTopicPost}
 */
proto.cashweb.registry.StoredMonadTopicPost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.MonadTopicPost;
      reader.readMessage(value,proto.cashweb.registry.MonadTopicPost.deserializeBinaryFromReader);
      msg.setPost(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSenderAddress(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTxHash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNetworkTag(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCborPostFrame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.StoredMonadTopicPost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.StoredMonadTopicPost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadTopicPost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPost();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cashweb.registry.MonadTopicPost.serializeBinaryToWriter
    );
  }
  f = message.getSenderAddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTxHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getNetworkTag_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getCborPostFrame_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional MonadTopicPost post = 1;
 * @return {?proto.cashweb.registry.MonadTopicPost}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getPost = function() {
  return /** @type{?proto.cashweb.registry.MonadTopicPost} */ (
    jspb.Message.getWrapperField(this, proto.cashweb.registry.MonadTopicPost, 1));
};


/**
 * @param {?proto.cashweb.registry.MonadTopicPost|undefined} value
 * @return {!proto.cashweb.registry.StoredMonadTopicPost} returns this
*/
proto.cashweb.registry.StoredMonadTopicPost.prototype.setPost = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cashweb.registry.StoredMonadTopicPost} returns this
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.clearPost = function() {
  return this.setPost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.hasPost = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes sender_address = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getSenderAddress = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes sender_address = 2;
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getSenderAddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSenderAddress()));
};


/**
 * optional bytes sender_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getSenderAddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSenderAddress()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadTopicPost} returns this
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.setSenderAddress = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes tx_hash = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getTxHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes tx_hash = 3;
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getTxHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTxHash()));
};


/**
 * optional bytes tx_hash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getTxHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTxHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadTopicPost} returns this
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.setTxHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional int64 timestamp = 4;
 * @return {number}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.StoredMonadTopicPost} returns this
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes network_tag = 5;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getNetworkTag = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes network_tag = 5;
 * This is a type-conversion wrapper around `getNetworkTag()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getNetworkTag_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNetworkTag()));
};


/**
 * optional bytes network_tag = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNetworkTag()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getNetworkTag_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNetworkTag()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadTopicPost} returns this
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.setNetworkTag = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional bytes cbor_post_frame = 6;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getCborPostFrame = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes cbor_post_frame = 6;
 * This is a type-conversion wrapper around `getCborPostFrame()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getCborPostFrame_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCborPostFrame()));
};


/**
 * optional bytes cbor_post_frame = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCborPostFrame()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.getCborPostFrame_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCborPostFrame()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadTopicPost} returns this
 */
proto.cashweb.registry.StoredMonadTopicPost.prototype.setCborPostFrame = function(value) {
  return jspb.Message.setProto3BytesField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.StoredMonadTopicVoteEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.StoredMonadTopicVoteEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
targetPayloadHash: msg.getTargetPayloadHash_asB64(),
senderAddress: msg.getSenderAddress_asB64(),
txHash: msg.getTxHash_asB64(),
timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
weight: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.StoredMonadTopicVoteEntry}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.StoredMonadTopicVoteEntry;
  return proto.cashweb.registry.StoredMonadTopicVoteEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.StoredMonadTopicVoteEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.StoredMonadTopicVoteEntry}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTargetPayloadHash(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSenderAddress(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTxHash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setWeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.StoredMonadTopicVoteEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.StoredMonadTopicVoteEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetPayloadHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getSenderAddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTxHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeSint64(
      5,
      f
    );
  }
};


/**
 * optional bytes target_payload_hash = 1;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getTargetPayloadHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes target_payload_hash = 1;
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getTargetPayloadHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTargetPayloadHash()));
};


/**
 * optional bytes target_payload_hash = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getTargetPayloadHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTargetPayloadHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadTopicVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.setTargetPayloadHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes sender_address = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getSenderAddress = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes sender_address = 2;
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getSenderAddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSenderAddress()));
};


/**
 * optional bytes sender_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getSenderAddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSenderAddress()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadTopicVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.setSenderAddress = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes tx_hash = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getTxHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes tx_hash = 3;
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getTxHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTxHash()));
};


/**
 * optional bytes tx_hash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getTxHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTxHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadTopicVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.setTxHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional int64 timestamp = 4;
 * @return {number}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.StoredMonadTopicVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint64 weight = 5;
 * @return {number}
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.StoredMonadTopicVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadTopicVoteEntry.prototype.setWeight = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadTopicPostView.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadTopicPostView.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadTopicPostView} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicPostView.toObject = function(includeInstance, msg) {
  var f, obj = {
post: (f = msg.getPost()) && proto.cashweb.registry.StoredMonadTopicPost.toObject(includeInstance, f),
voteWeight: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadTopicPostView}
 */
proto.cashweb.registry.MonadTopicPostView.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadTopicPostView;
  return proto.cashweb.registry.MonadTopicPostView.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadTopicPostView} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadTopicPostView}
 */
proto.cashweb.registry.MonadTopicPostView.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.StoredMonadTopicPost;
      reader.readMessage(value,proto.cashweb.registry.StoredMonadTopicPost.deserializeBinaryFromReader);
      msg.setPost(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setVoteWeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicPostView.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadTopicPostView.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadTopicPostView} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicPostView.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPost();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cashweb.registry.StoredMonadTopicPost.serializeBinaryToWriter
    );
  }
  f = message.getVoteWeight();
  if (f !== 0) {
    writer.writeSint64(
      2,
      f
    );
  }
};


/**
 * optional StoredMonadTopicPost post = 1;
 * @return {?proto.cashweb.registry.StoredMonadTopicPost}
 */
proto.cashweb.registry.MonadTopicPostView.prototype.getPost = function() {
  return /** @type{?proto.cashweb.registry.StoredMonadTopicPost} */ (
    jspb.Message.getWrapperField(this, proto.cashweb.registry.StoredMonadTopicPost, 1));
};


/**
 * @param {?proto.cashweb.registry.StoredMonadTopicPost|undefined} value
 * @return {!proto.cashweb.registry.MonadTopicPostView} returns this
*/
proto.cashweb.registry.MonadTopicPostView.prototype.setPost = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cashweb.registry.MonadTopicPostView} returns this
 */
proto.cashweb.registry.MonadTopicPostView.prototype.clearPost = function() {
  return this.setPost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cashweb.registry.MonadTopicPostView.prototype.hasPost = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sint64 vote_weight = 2;
 * @return {number}
 */
proto.cashweb.registry.MonadTopicPostView.prototype.getVoteWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.MonadTopicPostView} returns this
 */
proto.cashweb.registry.MonadTopicPostView.prototype.setVoteWeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cashweb.registry.MonadTopicPostViews.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadTopicPostViews.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadTopicPostViews.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadTopicPostViews} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicPostViews.toObject = function(includeInstance, msg) {
  var f, obj = {
viewsList: jspb.Message.toObjectList(msg.getViewsList(),
    proto.cashweb.registry.MonadTopicPostView.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadTopicPostViews}
 */
proto.cashweb.registry.MonadTopicPostViews.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadTopicPostViews;
  return proto.cashweb.registry.MonadTopicPostViews.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadTopicPostViews} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadTopicPostViews}
 */
proto.cashweb.registry.MonadTopicPostViews.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.MonadTopicPostView;
      reader.readMessage(value,proto.cashweb.registry.MonadTopicPostView.deserializeBinaryFromReader);
      msg.addViews(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadTopicPostViews.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadTopicPostViews.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadTopicPostViews} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadTopicPostViews.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getViewsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.cashweb.registry.MonadTopicPostView.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MonadTopicPostView views = 1;
 * @return {!Array<!proto.cashweb.registry.MonadTopicPostView>}
 */
proto.cashweb.registry.MonadTopicPostViews.prototype.getViewsList = function() {
  return /** @type{!Array<!proto.cashweb.registry.MonadTopicPostView>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cashweb.registry.MonadTopicPostView, 1));
};


/**
 * @param {!Array<!proto.cashweb.registry.MonadTopicPostView>} value
 * @return {!proto.cashweb.registry.MonadTopicPostViews} returns this
*/
proto.cashweb.registry.MonadTopicPostViews.prototype.setViewsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.cashweb.registry.MonadTopicPostView=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cashweb.registry.MonadTopicPostView}
 */
proto.cashweb.registry.MonadTopicPostViews.prototype.addViews = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.cashweb.registry.MonadTopicPostView, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cashweb.registry.MonadTopicPostViews} returns this
 */
proto.cashweb.registry.MonadTopicPostViews.prototype.clearViewsList = function() {
  return this.setViewsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.TopicDiscoveryStats.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.TopicDiscoveryStats.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.TopicDiscoveryStats} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.TopicDiscoveryStats.toObject = function(includeInstance, msg) {
  var f, obj = {
postCount: jspb.Message.getFieldWithDefault(msg, 1, 0),
lastActivityMs: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.TopicDiscoveryStats}
 */
proto.cashweb.registry.TopicDiscoveryStats.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.TopicDiscoveryStats;
  return proto.cashweb.registry.TopicDiscoveryStats.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.TopicDiscoveryStats} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.TopicDiscoveryStats}
 */
proto.cashweb.registry.TopicDiscoveryStats.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPostCount(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastActivityMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.TopicDiscoveryStats.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.TopicDiscoveryStats.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.TopicDiscoveryStats} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.TopicDiscoveryStats.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPostCount();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getLastActivityMs();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional uint64 post_count = 1;
 * @return {number}
 */
proto.cashweb.registry.TopicDiscoveryStats.prototype.getPostCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.TopicDiscoveryStats} returns this
 */
proto.cashweb.registry.TopicDiscoveryStats.prototype.setPostCount = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 last_activity_ms = 2;
 * @return {number}
 */
proto.cashweb.registry.TopicDiscoveryStats.prototype.getLastActivityMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.TopicDiscoveryStats} returns this
 */
proto.cashweb.registry.TopicDiscoveryStats.prototype.setLastActivityMs = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.TopicDiscoveryEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.TopicDiscoveryEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.TopicDiscoveryEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
topic: jspb.Message.getFieldWithDefault(msg, 1, ""),
postCount: jspb.Message.getFieldWithDefault(msg, 2, 0),
lastActivityMs: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.TopicDiscoveryEntry}
 */
proto.cashweb.registry.TopicDiscoveryEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.TopicDiscoveryEntry;
  return proto.cashweb.registry.TopicDiscoveryEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.TopicDiscoveryEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.TopicDiscoveryEntry}
 */
proto.cashweb.registry.TopicDiscoveryEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTopic(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPostCount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastActivityMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.TopicDiscoveryEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.TopicDiscoveryEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.TopicDiscoveryEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPostCount();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getLastActivityMs();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string topic = 1;
 * @return {string}
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cashweb.registry.TopicDiscoveryEntry} returns this
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 post_count = 2;
 * @return {number}
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.getPostCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.TopicDiscoveryEntry} returns this
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.setPostCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 last_activity_ms = 3;
 * @return {number}
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.getLastActivityMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.TopicDiscoveryEntry} returns this
 */
proto.cashweb.registry.TopicDiscoveryEntry.prototype.setLastActivityMs = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cashweb.registry.ListTopicsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.ListTopicsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.ListTopicsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.ListTopicsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.ListTopicsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
entriesList: jspb.Message.toObjectList(msg.getEntriesList(),
    proto.cashweb.registry.TopicDiscoveryEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.ListTopicsResponse}
 */
proto.cashweb.registry.ListTopicsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.ListTopicsResponse;
  return proto.cashweb.registry.ListTopicsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.ListTopicsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.ListTopicsResponse}
 */
proto.cashweb.registry.ListTopicsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.TopicDiscoveryEntry;
      reader.readMessage(value,proto.cashweb.registry.TopicDiscoveryEntry.deserializeBinaryFromReader);
      msg.addEntries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.ListTopicsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.ListTopicsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.ListTopicsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.ListTopicsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.cashweb.registry.TopicDiscoveryEntry.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TopicDiscoveryEntry entries = 1;
 * @return {!Array<!proto.cashweb.registry.TopicDiscoveryEntry>}
 */
proto.cashweb.registry.ListTopicsResponse.prototype.getEntriesList = function() {
  return /** @type{!Array<!proto.cashweb.registry.TopicDiscoveryEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cashweb.registry.TopicDiscoveryEntry, 1));
};


/**
 * @param {!Array<!proto.cashweb.registry.TopicDiscoveryEntry>} value
 * @return {!proto.cashweb.registry.ListTopicsResponse} returns this
*/
proto.cashweb.registry.ListTopicsResponse.prototype.setEntriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.cashweb.registry.TopicDiscoveryEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cashweb.registry.TopicDiscoveryEntry}
 */
proto.cashweb.registry.ListTopicsResponse.prototype.addEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.cashweb.registry.TopicDiscoveryEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cashweb.registry.ListTopicsResponse} returns this
 */
proto.cashweb.registry.ListTopicsResponse.prototype.clearEntriesList = function() {
  return this.setEntriesList([]);
};


goog.object.extend(exports, proto.cashweb.registry);
