// source: forum_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

goog.exportSymbol('proto.cashweb.registry.MonadForumPost', null, global);
goog.exportSymbol('proto.cashweb.registry.MonadForumPostView', null, global);
goog.exportSymbol('proto.cashweb.registry.MonadForumVote', null, global);
goog.exportSymbol('proto.cashweb.registry.StoredMonadForumPost', null, global);
goog.exportSymbol('proto.cashweb.registry.StoredMonadForumVoteEntry', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadForumPost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.MonadForumPost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadForumPost.displayName = 'proto.cashweb.registry.MonadForumPost';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadForumVote = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.MonadForumVote, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadForumVote.displayName = 'proto.cashweb.registry.MonadForumVote';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.StoredMonadForumPost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.StoredMonadForumPost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.StoredMonadForumPost.displayName = 'proto.cashweb.registry.StoredMonadForumPost';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.StoredMonadForumVoteEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.StoredMonadForumVoteEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.StoredMonadForumVoteEntry.displayName = 'proto.cashweb.registry.StoredMonadForumVoteEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadForumPostView = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.MonadForumPostView, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadForumPostView.displayName = 'proto.cashweb.registry.MonadForumPostView';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadForumPost.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadForumPost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadForumPost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadForumPost.toObject = function(includeInstance, msg) {
  var f, obj = {
topic: jspb.Message.getFieldWithDefault(msg, 1, ""),
parentPostHash: msg.getParentPostHash_asB64(),
rawBurnTx: msg.getRawBurnTx_asB64(),
encryptedPayload: msg.getEncryptedPayload_asB64(),
payloadHash: msg.getPayloadHash_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadForumPost}
 */
proto.cashweb.registry.MonadForumPost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadForumPost;
  return proto.cashweb.registry.MonadForumPost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadForumPost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadForumPost}
 */
proto.cashweb.registry.MonadForumPost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTopic(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setParentPostHash(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawBurnTx(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncryptedPayload(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPayloadHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumPost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadForumPost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadForumPost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadForumPost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getParentPostHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getRawBurnTx_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getEncryptedPayload_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getPayloadHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional string topic = 1;
 * @return {string}
 */
proto.cashweb.registry.MonadForumPost.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cashweb.registry.MonadForumPost} returns this
 */
proto.cashweb.registry.MonadForumPost.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes parent_post_hash = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadForumPost.prototype.getParentPostHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes parent_post_hash = 2;
 * This is a type-conversion wrapper around `getParentPostHash()`
 * @return {string}
 */
proto.cashweb.registry.MonadForumPost.prototype.getParentPostHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getParentPostHash()));
};


/**
 * optional bytes parent_post_hash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getParentPostHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumPost.prototype.getParentPostHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getParentPostHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadForumPost} returns this
 */
proto.cashweb.registry.MonadForumPost.prototype.setParentPostHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes raw_burn_tx = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadForumPost.prototype.getRawBurnTx = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes raw_burn_tx = 3;
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {string}
 */
proto.cashweb.registry.MonadForumPost.prototype.getRawBurnTx_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawBurnTx()));
};


/**
 * optional bytes raw_burn_tx = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumPost.prototype.getRawBurnTx_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawBurnTx()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadForumPost} returns this
 */
proto.cashweb.registry.MonadForumPost.prototype.setRawBurnTx = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes encrypted_payload = 4;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadForumPost.prototype.getEncryptedPayload = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes encrypted_payload = 4;
 * This is a type-conversion wrapper around `getEncryptedPayload()`
 * @return {string}
 */
proto.cashweb.registry.MonadForumPost.prototype.getEncryptedPayload_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncryptedPayload()));
};


/**
 * optional bytes encrypted_payload = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncryptedPayload()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumPost.prototype.getEncryptedPayload_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncryptedPayload()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadForumPost} returns this
 */
proto.cashweb.registry.MonadForumPost.prototype.setEncryptedPayload = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bytes payload_hash = 5;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadForumPost.prototype.getPayloadHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes payload_hash = 5;
 * This is a type-conversion wrapper around `getPayloadHash()`
 * @return {string}
 */
proto.cashweb.registry.MonadForumPost.prototype.getPayloadHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPayloadHash()));
};


/**
 * optional bytes payload_hash = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPayloadHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumPost.prototype.getPayloadHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPayloadHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadForumPost} returns this
 */
proto.cashweb.registry.MonadForumPost.prototype.setPayloadHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadForumVote.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadForumVote.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadForumVote} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadForumVote.toObject = function(includeInstance, msg) {
  var f, obj = {
targetPayloadHash: msg.getTargetPayloadHash_asB64(),
rawBurnTx: msg.getRawBurnTx_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadForumVote}
 */
proto.cashweb.registry.MonadForumVote.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadForumVote;
  return proto.cashweb.registry.MonadForumVote.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadForumVote} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadForumVote}
 */
proto.cashweb.registry.MonadForumVote.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTargetPayloadHash(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawBurnTx(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumVote.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadForumVote.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadForumVote} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadForumVote.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetPayloadHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getRawBurnTx_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional bytes target_payload_hash = 1;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadForumVote.prototype.getTargetPayloadHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes target_payload_hash = 1;
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {string}
 */
proto.cashweb.registry.MonadForumVote.prototype.getTargetPayloadHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTargetPayloadHash()));
};


/**
 * optional bytes target_payload_hash = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumVote.prototype.getTargetPayloadHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTargetPayloadHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadForumVote} returns this
 */
proto.cashweb.registry.MonadForumVote.prototype.setTargetPayloadHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes raw_burn_tx = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadForumVote.prototype.getRawBurnTx = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes raw_burn_tx = 2;
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {string}
 */
proto.cashweb.registry.MonadForumVote.prototype.getRawBurnTx_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawBurnTx()));
};


/**
 * optional bytes raw_burn_tx = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumVote.prototype.getRawBurnTx_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawBurnTx()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadForumVote} returns this
 */
proto.cashweb.registry.MonadForumVote.prototype.setRawBurnTx = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.StoredMonadForumPost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.StoredMonadForumPost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadForumPost.toObject = function(includeInstance, msg) {
  var f, obj = {
post: (f = msg.getPost()) && proto.cashweb.registry.MonadForumPost.toObject(includeInstance, f),
senderAddress: msg.getSenderAddress_asB64(),
txHash: msg.getTxHash_asB64(),
timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
networkTag: msg.getNetworkTag_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.StoredMonadForumPost}
 */
proto.cashweb.registry.StoredMonadForumPost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.StoredMonadForumPost;
  return proto.cashweb.registry.StoredMonadForumPost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.StoredMonadForumPost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.StoredMonadForumPost}
 */
proto.cashweb.registry.StoredMonadForumPost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.MonadForumPost;
      reader.readMessage(value,proto.cashweb.registry.MonadForumPost.deserializeBinaryFromReader);
      msg.setPost(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSenderAddress(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTxHash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNetworkTag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.StoredMonadForumPost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.StoredMonadForumPost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadForumPost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPost();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cashweb.registry.MonadForumPost.serializeBinaryToWriter
    );
  }
  f = message.getSenderAddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTxHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getNetworkTag_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional MonadForumPost post = 1;
 * @return {?proto.cashweb.registry.MonadForumPost}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getPost = function() {
  return /** @type{?proto.cashweb.registry.MonadForumPost} */ (
    jspb.Message.getWrapperField(this, proto.cashweb.registry.MonadForumPost, 1));
};


/**
 * @param {?proto.cashweb.registry.MonadForumPost|undefined} value
 * @return {!proto.cashweb.registry.StoredMonadForumPost} returns this
*/
proto.cashweb.registry.StoredMonadForumPost.prototype.setPost = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cashweb.registry.StoredMonadForumPost} returns this
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.clearPost = function() {
  return this.setPost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.hasPost = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes sender_address = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getSenderAddress = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes sender_address = 2;
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getSenderAddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSenderAddress()));
};


/**
 * optional bytes sender_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getSenderAddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSenderAddress()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadForumPost} returns this
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.setSenderAddress = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes tx_hash = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getTxHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes tx_hash = 3;
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getTxHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTxHash()));
};


/**
 * optional bytes tx_hash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getTxHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTxHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadForumPost} returns this
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.setTxHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional int64 timestamp = 4;
 * @return {number}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.StoredMonadForumPost} returns this
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes network_tag = 5;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getNetworkTag = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes network_tag = 5;
 * This is a type-conversion wrapper around `getNetworkTag()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getNetworkTag_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNetworkTag()));
};


/**
 * optional bytes network_tag = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNetworkTag()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.getNetworkTag_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNetworkTag()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadForumPost} returns this
 */
proto.cashweb.registry.StoredMonadForumPost.prototype.setNetworkTag = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.StoredMonadForumVoteEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.StoredMonadForumVoteEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
targetPayloadHash: msg.getTargetPayloadHash_asB64(),
senderAddress: msg.getSenderAddress_asB64(),
txHash: msg.getTxHash_asB64(),
timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
weight: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.StoredMonadForumVoteEntry}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.StoredMonadForumVoteEntry;
  return proto.cashweb.registry.StoredMonadForumVoteEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.StoredMonadForumVoteEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.StoredMonadForumVoteEntry}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTargetPayloadHash(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSenderAddress(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTxHash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setWeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.StoredMonadForumVoteEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.StoredMonadForumVoteEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetPayloadHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getSenderAddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTxHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeSint64(
      5,
      f
    );
  }
};


/**
 * optional bytes target_payload_hash = 1;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getTargetPayloadHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes target_payload_hash = 1;
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getTargetPayloadHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTargetPayloadHash()));
};


/**
 * optional bytes target_payload_hash = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTargetPayloadHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getTargetPayloadHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTargetPayloadHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadForumVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.setTargetPayloadHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes sender_address = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getSenderAddress = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes sender_address = 2;
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getSenderAddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSenderAddress()));
};


/**
 * optional bytes sender_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getSenderAddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSenderAddress()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadForumVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.setSenderAddress = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes tx_hash = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getTxHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes tx_hash = 3;
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getTxHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTxHash()));
};


/**
 * optional bytes tx_hash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getTxHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTxHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadForumVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.setTxHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional int64 timestamp = 4;
 * @return {number}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.StoredMonadForumVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint64 weight = 5;
 * @return {number}
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.StoredMonadForumVoteEntry} returns this
 */
proto.cashweb.registry.StoredMonadForumVoteEntry.prototype.setWeight = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadForumPostView.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadForumPostView.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadForumPostView} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadForumPostView.toObject = function(includeInstance, msg) {
  var f, obj = {
post: (f = msg.getPost()) && proto.cashweb.registry.StoredMonadForumPost.toObject(includeInstance, f),
voteWeight: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadForumPostView}
 */
proto.cashweb.registry.MonadForumPostView.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadForumPostView;
  return proto.cashweb.registry.MonadForumPostView.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadForumPostView} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadForumPostView}
 */
proto.cashweb.registry.MonadForumPostView.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.StoredMonadForumPost;
      reader.readMessage(value,proto.cashweb.registry.StoredMonadForumPost.deserializeBinaryFromReader);
      msg.setPost(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setVoteWeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadForumPostView.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadForumPostView.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadForumPostView} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadForumPostView.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPost();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cashweb.registry.StoredMonadForumPost.serializeBinaryToWriter
    );
  }
  f = message.getVoteWeight();
  if (f !== 0) {
    writer.writeSint64(
      2,
      f
    );
  }
};


/**
 * optional StoredMonadForumPost post = 1;
 * @return {?proto.cashweb.registry.StoredMonadForumPost}
 */
proto.cashweb.registry.MonadForumPostView.prototype.getPost = function() {
  return /** @type{?proto.cashweb.registry.StoredMonadForumPost} */ (
    jspb.Message.getWrapperField(this, proto.cashweb.registry.StoredMonadForumPost, 1));
};


/**
 * @param {?proto.cashweb.registry.StoredMonadForumPost|undefined} value
 * @return {!proto.cashweb.registry.MonadForumPostView} returns this
*/
proto.cashweb.registry.MonadForumPostView.prototype.setPost = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cashweb.registry.MonadForumPostView} returns this
 */
proto.cashweb.registry.MonadForumPostView.prototype.clearPost = function() {
  return this.setPost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cashweb.registry.MonadForumPostView.prototype.hasPost = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sint64 vote_weight = 2;
 * @return {number}
 */
proto.cashweb.registry.MonadForumPostView.prototype.getVoteWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.MonadForumPostView} returns this
 */
proto.cashweb.registry.MonadForumPostView.prototype.setVoteWeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.cashweb.registry);
