// source: monad_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

goog.exportSymbol('proto.cashweb.registry.MonadStampedMessage', null, global);
goog.exportSymbol('proto.cashweb.registry.StoredMonadMessage', null, global);
goog.exportSymbol('proto.cashweb.registry.StoredMonadMessages', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.MonadStampedMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.MonadStampedMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.MonadStampedMessage.displayName = 'proto.cashweb.registry.MonadStampedMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.StoredMonadMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cashweb.registry.StoredMonadMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.StoredMonadMessage.displayName = 'proto.cashweb.registry.StoredMonadMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cashweb.registry.StoredMonadMessages = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cashweb.registry.StoredMonadMessages.repeatedFields_, null);
};
goog.inherits(proto.cashweb.registry.StoredMonadMessages, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cashweb.registry.StoredMonadMessages.displayName = 'proto.cashweb.registry.StoredMonadMessages';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.MonadStampedMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.MonadStampedMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadStampedMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
rawBurnTx: msg.getRawBurnTx_asB64(),
encryptedPayload: msg.getEncryptedPayload_asB64(),
payloadHash: msg.getPayloadHash_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.MonadStampedMessage}
 */
proto.cashweb.registry.MonadStampedMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.MonadStampedMessage;
  return proto.cashweb.registry.MonadStampedMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.MonadStampedMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.MonadStampedMessage}
 */
proto.cashweb.registry.MonadStampedMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawBurnTx(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncryptedPayload(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPayloadHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.MonadStampedMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.MonadStampedMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.MonadStampedMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRawBurnTx_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getEncryptedPayload_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getPayloadHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional bytes raw_burn_tx = 1;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getRawBurnTx = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes raw_burn_tx = 1;
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {string}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getRawBurnTx_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawBurnTx()));
};


/**
 * optional bytes raw_burn_tx = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawBurnTx()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getRawBurnTx_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawBurnTx()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadStampedMessage} returns this
 */
proto.cashweb.registry.MonadStampedMessage.prototype.setRawBurnTx = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes encrypted_payload = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getEncryptedPayload = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes encrypted_payload = 2;
 * This is a type-conversion wrapper around `getEncryptedPayload()`
 * @return {string}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getEncryptedPayload_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncryptedPayload()));
};


/**
 * optional bytes encrypted_payload = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncryptedPayload()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getEncryptedPayload_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncryptedPayload()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadStampedMessage} returns this
 */
proto.cashweb.registry.MonadStampedMessage.prototype.setEncryptedPayload = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes payload_hash = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getPayloadHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes payload_hash = 3;
 * This is a type-conversion wrapper around `getPayloadHash()`
 * @return {string}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getPayloadHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPayloadHash()));
};


/**
 * optional bytes payload_hash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPayloadHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.MonadStampedMessage.prototype.getPayloadHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPayloadHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.MonadStampedMessage} returns this
 */
proto.cashweb.registry.MonadStampedMessage.prototype.setPayloadHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.StoredMonadMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.StoredMonadMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
message: (f = msg.getMessage()) && proto.cashweb.registry.MonadStampedMessage.toObject(includeInstance, f),
senderAddress: msg.getSenderAddress_asB64(),
txHash: msg.getTxHash_asB64(),
timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
networkTag: msg.getNetworkTag_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.StoredMonadMessage}
 */
proto.cashweb.registry.StoredMonadMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.StoredMonadMessage;
  return proto.cashweb.registry.StoredMonadMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.StoredMonadMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.StoredMonadMessage}
 */
proto.cashweb.registry.StoredMonadMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.MonadStampedMessage;
      reader.readMessage(value,proto.cashweb.registry.MonadStampedMessage.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSenderAddress(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTxHash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setNetworkTag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.StoredMonadMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.StoredMonadMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cashweb.registry.MonadStampedMessage.serializeBinaryToWriter
    );
  }
  f = message.getSenderAddress_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTxHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getNetworkTag_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional MonadStampedMessage message = 1;
 * @return {?proto.cashweb.registry.MonadStampedMessage}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getMessage = function() {
  return /** @type{?proto.cashweb.registry.MonadStampedMessage} */ (
    jspb.Message.getWrapperField(this, proto.cashweb.registry.MonadStampedMessage, 1));
};


/**
 * @param {?proto.cashweb.registry.MonadStampedMessage|undefined} value
 * @return {!proto.cashweb.registry.StoredMonadMessage} returns this
*/
proto.cashweb.registry.StoredMonadMessage.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cashweb.registry.StoredMonadMessage} returns this
 */
proto.cashweb.registry.StoredMonadMessage.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes sender_address = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getSenderAddress = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes sender_address = 2;
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getSenderAddress_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSenderAddress()));
};


/**
 * optional bytes sender_address = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSenderAddress()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getSenderAddress_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSenderAddress()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadMessage} returns this
 */
proto.cashweb.registry.StoredMonadMessage.prototype.setSenderAddress = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes tx_hash = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getTxHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes tx_hash = 3;
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getTxHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTxHash()));
};


/**
 * optional bytes tx_hash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTxHash()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getTxHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTxHash()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadMessage} returns this
 */
proto.cashweb.registry.StoredMonadMessage.prototype.setTxHash = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional int64 timestamp = 4;
 * @return {number}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cashweb.registry.StoredMonadMessage} returns this
 */
proto.cashweb.registry.StoredMonadMessage.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes network_tag = 5;
 * @return {!(string|Uint8Array)}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getNetworkTag = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes network_tag = 5;
 * This is a type-conversion wrapper around `getNetworkTag()`
 * @return {string}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getNetworkTag_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getNetworkTag()));
};


/**
 * optional bytes network_tag = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNetworkTag()`
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadMessage.prototype.getNetworkTag_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getNetworkTag()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cashweb.registry.StoredMonadMessage} returns this
 */
proto.cashweb.registry.StoredMonadMessage.prototype.setNetworkTag = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cashweb.registry.StoredMonadMessages.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cashweb.registry.StoredMonadMessages.prototype.toObject = function(opt_includeInstance) {
  return proto.cashweb.registry.StoredMonadMessages.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cashweb.registry.StoredMonadMessages} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadMessages.toObject = function(includeInstance, msg) {
  var f, obj = {
messagesList: jspb.Message.toObjectList(msg.getMessagesList(),
    proto.cashweb.registry.StoredMonadMessage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cashweb.registry.StoredMonadMessages}
 */
proto.cashweb.registry.StoredMonadMessages.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cashweb.registry.StoredMonadMessages;
  return proto.cashweb.registry.StoredMonadMessages.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cashweb.registry.StoredMonadMessages} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cashweb.registry.StoredMonadMessages}
 */
proto.cashweb.registry.StoredMonadMessages.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cashweb.registry.StoredMonadMessage;
      reader.readMessage(value,proto.cashweb.registry.StoredMonadMessage.deserializeBinaryFromReader);
      msg.addMessages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cashweb.registry.StoredMonadMessages.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cashweb.registry.StoredMonadMessages.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cashweb.registry.StoredMonadMessages} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cashweb.registry.StoredMonadMessages.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.cashweb.registry.StoredMonadMessage.serializeBinaryToWriter
    );
  }
};


/**
 * repeated StoredMonadMessage messages = 1;
 * @return {!Array<!proto.cashweb.registry.StoredMonadMessage>}
 */
proto.cashweb.registry.StoredMonadMessages.prototype.getMessagesList = function() {
  return /** @type{!Array<!proto.cashweb.registry.StoredMonadMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cashweb.registry.StoredMonadMessage, 1));
};


/**
 * @param {!Array<!proto.cashweb.registry.StoredMonadMessage>} value
 * @return {!proto.cashweb.registry.StoredMonadMessages} returns this
*/
proto.cashweb.registry.StoredMonadMessages.prototype.setMessagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.cashweb.registry.StoredMonadMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cashweb.registry.StoredMonadMessage}
 */
proto.cashweb.registry.StoredMonadMessages.prototype.addMessages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.cashweb.registry.StoredMonadMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cashweb.registry.StoredMonadMessages} returns this
 */
proto.cashweb.registry.StoredMonadMessages.prototype.clearMessagesList = function() {
  return this.setMessagesList([]);
};


goog.object.extend(exports, proto.cashweb.registry);
